// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SliderDemo: typeof import('./src/components/SliderDemo.vue')['default']
    TimePickerDemo: typeof import('./src/components/TimePickerDemo.vue')['default']
    TreeSelectDemo: typeof import('./src/components/TreeSelectDemo.vue')['default']
  }
}

export { }
